---
title: "female_BAL6_preprocessing_analysis"
author: "Trevor Kwan"
date: "19/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(dplyr)
library(patchwork)
library(metap)
library(multtest)
# untar("GSM4762157_BAL6_out.tar.gz", exdir = "BAL6/CEL")
```

```{r}
# setup the Seurat object
options(digits = 3)

BAL6.data <- Read10X(data.dir = ".././data/BAL6/")
BAL6 <- CreateSeuratObject(counts = BAL6.data, project = "BAL6", min.cells = 3, min.features = 200)
BAL6$var <- "BAL6"
```

```{r}
# filter genes
BAL6[["percent.mt"]] <- PercentageFeatureSet(BAL6, pattern = "^MT-")

# pre-filtering
VlnPlot(BAL6, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

plot1 <- FeatureScatter(BAL6, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(BAL6, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

BAL6 <- subset(BAL6, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

# post-filtering
VlnPlot(BAL6, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
# normalize the data
BAL6 <- NormalizeData(BAL6, normalization.method = "LogNormalize", scale.factor = 10000)

# feature selection (identifying highly variable features/genes)
BAL6 <- FindVariableFeatures(BAL6, selection.method = "vst", nfeatures = 2000)

# identify the 10 most highly variable genes
top10 <- head(VariableFeatures(BAL6), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(BAL6)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1
plot2
```

```{r}
# scaling
all.genes <- rownames(BAL6)
BAL6 <- ScaleData(BAL6, features = all.genes)
```

```{r}
# pca (linear dimension reduction)
BAL6 <- RunPCA(BAL6, features = VariableFeatures(object = BAL6))

# visualize PCA
VizDimLoadings(BAL6, dims = 1:2, reduction = "pca")
DimPlot(BAL6, reduction = "pca")
DimHeatmap(BAL6, dims = 1, cells = 500, balanced = TRUE)
```






